# Generated by Django 5.2 on 2025-06-25 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default='employee', max_length=30, unique=True),
        ),
    ]
