# Generated by Django 5.2 on 2025-05-27 22:15

import django.db.models.deletion
import utils.acc_num_generate
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0002_alter_individualdetails_birth_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcquiringContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_num', models.CharField(max_length=20, unique=True)),
                ('acc_num', models.CharField(default=utils.acc_num_generate.generate_account_number, max_length=28, unique=True)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('commission', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.client')),
            ],
        ),
        migrations.CreateModel(
            name='AcquiringTransactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_transaction', models.DateTimeField(auto_now_add=True)),
                ('sum_transaction', models.DecimalField(decimal_places=2, max_digits=12)),
                ('num_card', models.CharField(max_length=20)),
                ('sum_commission', models.DecimalField(decimal_places=2, max_digits=12)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='acquiring.acquiringcontract')),
            ],
        ),
    ]
