# Generated by Django 5.2 on 2025-05-27 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acquiring', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acquiringcontract',
            name='contract_num',
            field=models.CharField(default='2025-05-28-583233623', max_length=20, unique=True),
        ),
    ]
