# Generated by Django 5.2 on 2025-05-29 00:21

import utils.contract_num_generate
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acquiring', '0002_alter_acquiringcontract_contract_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acquiringcontract',
            name='contract_num',
            field=models.CharField(default=utils.contract_num_generate.generate_contract_number, max_length=20, unique=True),
        ),
    ]
