# Generated by Django 5.2 on 2025-07-29 00:51

import django.db.models.deletion
import utils.contract_num_generate
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('contract_number', models.CharField(default=utils.contract_num_generate.generate_contract_number, max_length=28, unique=True)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('loan_term', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Paid Off', 'Paid Off')], default='Active', max_length=10)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_contract', to='clients.client')),
            ],
        ),
        migrations.CreateModel(
            name='CreditBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_balance', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('contract', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='credit.creditcontract')),
            ],
        ),
        migrations.CreateModel(
            name='CreditTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('transaction_date', models.DateTimeField(auto_now_add=True)),
                ('balance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_transactions', to='credit.creditbalance')),
            ],
        ),
        migrations.CreateModel(
            name='RequestCredit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_request', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('term_months', models.IntegerField()),
                ('request_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Canceled', 'Cancelled')], default='Pending', max_length=10)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_credits', to='clients.client')),
            ],
        ),
        migrations.AddField(
            model_name='creditcontract',
            name='request_credit',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='credit.requestcredit'),
        ),
    ]
